import { vars } from 'nativewind';

/** Variables CSS para NativeWind — se aplican en la raíz vía style={themes[scheme]} */
export const cromaticVars = {
  light: vars({
    '--color-surface-bright': '#fff8f1',
    '--color-accent-warm': '#d9d2c5',
    '--color-border-subtle': 'rgba(36, 31, 26, 0.08)',
    '--color-outline': '#7e766e',
    '--color-surface-container-lowest': '#ffffff',
    '--color-primary-container': '#241f1a',
    '--color-inverse-surface': '#32302c',
    '--color-surface-container': '#f3ede6',
    '--color-on-secondary-container': '#66645f',
    '--color-secondary': '#605e59',
    '--color-primary': '#0b0704',
    '--color-on-surface-variant': '#4c463f',
    '--color-on-primary': '#ffffff',
    '--color-secondary-container': '#e6e2db',
    '--color-paper-bg': '#faf6ef',
    '--color-background': '#fff8f1',
    '--color-surface-container-highest': '#e7e2db',
    '--color-on-background': '#1d1b17',
    '--color-inverse-primary': '#cfc5bd',
    '--color-surface': '#fff8f1',
    '--color-on-surface': '#1d1b17',
    '--color-surface-container-low': '#f9f3eb',
    '--color-surface-dim': '#dfd9d2',
    '--color-outline-variant': '#cfc5bc',
    '--color-surface-variant': '#e7e2db',
    '--color-surface-container-high': '#ede7e0',
    '--color-ink-text': '#241f1a',
    '--color-tertiary': '#07080b',
  }),
  dark: vars({
    '--color-surface-bright': '#24201c',
    '--color-accent-warm': '#5a554e',
    '--color-border-subtle': 'rgba(255, 255, 255, 0.12)',
    '--color-outline': '#9a9590',
    '--color-surface-container-lowest': '#2e2a26',
    '--color-primary-container': '#f9f3eb',
    '--color-inverse-surface': '#e7e2db',
    '--color-surface-container': '#2a2622',
    '--color-on-secondary-container': '#b0aca6',
    '--color-secondary': '#b0aca6',
    '--color-primary': '#ffffff',
    '--color-on-surface-variant': '#c8c4be',
    '--color-on-primary': '#1a1714',
    '--color-secondary-container': '#3a3632',
    '--color-paper-bg': '#1a1714',
    '--color-background': '#1a1714',
    '--color-surface-container-highest': '#3a3632',
    '--color-on-background': '#ffffff',
    '--color-inverse-primary': '#645d57',
    '--color-surface': '#1a1714',
    '--color-on-surface': '#ffffff',
    '--color-surface-container-low': '#24201c',
    '--color-surface-dim': '#12100e',
    '--color-outline-variant': '#5a554e',
    '--color-surface-variant': '#322e2a',
    '--color-surface-container-high': '#322e2a',
    '--color-ink-text': '#ffffff',
    '--color-tertiary': '#f9f3eb',
  }),
} as const;
