/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fff8f1",
        "accent-warm": "#D9D2C5",
        "on-tertiary-fixed": "#1a1b1e",
        "tertiary-container": "#1f2023",
        "on-secondary-fixed-variant": "#484742",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "border-subtle": "rgba(36, 31, 26, 0.08)",
        "outline": "#7e766e",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c7c6ca",
        "primary-container": "#241f1a",
        "inverse-surface": "#32302c",
        "surface-container": "#f3ede6",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1c1c18",
        "error-container": "#ffdad6",
        "on-primary-container": "#8e867f",
        "on-tertiary-container": "#87878b",
        "inverse-on-surface": "#f6f0e9",
        "tertiary-fixed": "#e3e2e6",
        "on-primary-fixed-variant": "#4c4640",
        "on-secondary-container": "#66645f",
        "secondary-fixed-dim": "#c9c6c0",
        "primary-fixed-dim": "#cfc5bd",
        "secondary": "#605e59",
        "on-tertiary-fixed-variant": "#46474a",
        "primary": "#0b0704",
        "on-surface-variant": "#4c463f",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-container": "#e6e2db",
        "paper-bg": "#FAF6EF",
        "background": "#fff8f1",
        "on-primary-fixed": "#201b16",
        "surface-container-highest": "#e7e2db",
        "on-background": "#1d1b17",
        "inverse-primary": "#cfc5bd",
        "surface": "#fff8f1",
        "on-surface": "#1d1b17",
        "surface-container-low": "#f9f3eb",
        "on-error-container": "#93000a",
        "surface-dim": "#dfd9d2",
        "outline-variant": "#cfc5bc",
        "surface-variant": "#e7e2db",
        "surface-container-high": "#ede7e0",
        "secondary-fixed": "#e6e2db",
        "primary-fixed": "#ebe1d8",
        "surface-tint": "#645d57",
        "ink-text": "#241F1A",
        "tertiary": "#07080b"
      },
      spacing: {
        "touch-target": "44px",
        "section-gap": "80px",
        "unit": "4px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-caps": ["Inter-SemiBold"],
        "display-lg": ["PlayfairDisplay-Bold"],
        "headline-md": ["PlayfairDisplay-SemiBold"],
        "body-lg": ["Inter"],
        "headline-sm": ["PlayfairDisplay-SemiBold"],
        "display-lg-mobile": ["PlayfairDisplay-Bold"],
        "body-md": ["Inter"],
        "button-text": ["Inter-Medium"]
      }
    },
  },
  plugins: [],
}
