/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "var(--color-surface-bright)",
        "accent-warm": "var(--color-accent-warm)",
        "on-tertiary-fixed": "#1a1b1e",
        "tertiary-container": "#1f2023",
        "on-secondary-fixed-variant": "#484742",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "border-subtle": "var(--color-border-subtle)",
        "outline": "var(--color-outline)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "tertiary-fixed-dim": "#c7c6ca",
        "primary-container": "var(--color-primary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-container": "var(--color-surface-container)",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#1c1c18",
        "error-container": "#ffdad6",
        "on-primary-container": "#8e867f",
        "on-tertiary-container": "#87878b",
        "inverse-on-surface": "#f6f0e9",
        "tertiary-fixed": "#e3e2e6",
        "on-primary-fixed-variant": "#4c4640",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed-dim": "#c9c6c0",
        "primary-fixed-dim": "#cfc5bd",
        "secondary": "var(--color-secondary)",
        "on-tertiary-fixed-variant": "#46474a",
        "primary": "var(--color-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-error": "#ffffff",
        "on-primary": "var(--color-on-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "paper-bg": "var(--color-paper-bg)",
        "background": "var(--color-background)",
        "on-primary-fixed": "#201b16",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-background": "var(--color-on-background)",
        "inverse-primary": "var(--color-inverse-primary)",
        "surface": "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-error-container": "#93000a",
        "surface-dim": "var(--color-surface-dim)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-high": "var(--color-surface-container-high)",
        "secondary-fixed": "#e6e2db",
        "primary-fixed": "#ebe1d8",
        "surface-tint": "#645d57",
        "ink-text": "var(--color-ink-text)",
        "tertiary": "var(--color-tertiary)"
      },
      spacing: {
        "touch-target": "44px",
        "section-gap": "80px",
        "unit": "4px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "label-caps": ["Inter-SemiBold"],
        "display-lg": ["PlayfairDisplay-Bold"],
        "headline-md": ["PlayfairDisplay-SemiBold"],
        "body-lg": ["Inter"],
        "headline-sm": ["PlayfairDisplay-SemiBold"],
        "display-lg-mobile": ["PlayfairDisplay-Bold"],
        "body-md": ["Inter"],
        "button-text": ["Inter-Medium"]
      }
    },
  },
  plugins: [],
}
